### ISSUE TITLE
Web Map interface with Intensity (Severity) Heat Maps

### ISSUE THREAD

**Issue by OkomoJacob** [opensource254/covid-19-web-react#13]
Good job here!
I love React because it is react! The UI/UX is a real beauty. Can we add a web map interface of the cases showing colour density or even using density dot maps to give an instant overview of which parts are spatially prone to cases?
- A good representative example can be viewed [here](https://mangomap.com/examples/maps/51686/heat-map#)

- Thank you

**Comment by StanleyMasinde** [comment]
Hi, @OkomoJacob. sorry this was not seen early. We'd love your contributions in this org though.
