### ISSUE TITLE
:bug: comma placement 

### ISSUE THREAD

**Issue by conradKE** [opensource254/covid-19-web-react#2]
12,03,143

should be

1,203,143

**Comment by StanleyMasinde** [comment]
I have not rea

> 12,03,143
> 
> should be
> 
> 1,203,143

I have not read the code but I think they are using number internationalisation. I'd suggest the use the Intl interface and set the local to en_us

**Comment by billthebuilder** [comment]
I'll have a look at it later

**Comment by cyrus43** [comment]
Have changed but bado It's still displaying the same. Lemme use your method nione

**Comment by StanleyMasinde** [comment]
> Have changed but bado It's still displaying the same. Lemme use your method nione

Please link the PR @cyrus43
