### ISSUE TITLE
The countries page is blank

### ISSUE THREAD

**Issue by StanleyMasinde** [opensource254/covid-19-web-react#7]
The countries page is blank may be due to the changes in the API or something.

1. Please investigate
2. Please add a friendly error handler to tell the user that something is wrong

**Comment by billthebuilder** [comment]
> The countries page is blank may be due to the changes in the API or something.
> 
> 1. Please investigate
> 2. Please add a friendly error handler to tell the user that something is wrong

I've noticed, seems the error is from the API, something changed. Let me investigate

**Comment by StanleyMasinde** [comment]
Hapo kwenye umecall to locale string kuna kwenye umepass null values

> > The countries page is blank may be due to the changes in the API or something.
> > 
> > 1. Please investigate
> > 2. Please add a friendly error handler to tell the user that something is wrong
> 
> I've noticed, seems the error is from the API, something changed. Let me investigate

Hapo kwenye umecall to locale string kuna kwenye umepass null values replace null with 0 or something

**Comment by billthebuilder** [comment]
> Hapo kwenye umecall to locale string kuna kwenye umepass null values
> 
> > > The countries page is blank may be due to the changes in the API or something.
> > > 
> > > 1. Please investigate
> > > 2. Please add a friendly error handler to tell the user that something is wrong
> > 
> > I've noticed, seems the error is from the API, something changed. Let me investigate
> 
> Hapo kwenye umecall to locale string kuna kwenye umepass null values replace null with 0 or something

I've located the problem, seems UK data is returning a null value on recoveries so when you apply `.toLocaleString` Its being applied on a null value, which makes the whole section crash. I've applied a conditional that checks for null values and returns a zero. Submitting PR shortly

**Comment by StanleyMasinde** [comment]
> > Hapo kwenye umecall to locale string kuna kwenye umepass null values
> > > > The countries page is blank may be due to the changes in the API or something.
> > > > 
> > > > 1. Please investigate
> > > > 2. Please add a friendly error handler to tell the user that something is wrong
> > > 
> > > 
> > > I've noticed, seems the error is from the API, something changed. Let me investigate
> > 
> > 
> > Hapo kwenye umecall to locale string kuna kwenye umepass null values replace null with 0 or something
> 
> I've located the problem, seems UK data is returning a null value on recoveries so when you apply `.toLocaleString` Its being applied on a null value, which makes the whole section crash. I've applied a conditional that checks for null values and returns a zero. Submitting PR shortly

Awesome
